### ISSUE TITLE
Some Icelandic posters show wrong sunset

### ISSUE THREAD

**Issue by leobut** [leventerevesz/sunlight-calendar#2]
When creating the poster for a location in the north of Iceland, the sunset for the location is wrong.

How to reproduce:

- Have a look at the time around  Jun 21
- Latitude: 65.4
- Longitude: -23
- Altitude: 65
- Timezone Offset: 0

When I debug this and have a look at the calculated times from SunCalc, I can see that the calculations are correct, it's only wrong in the generated poster. The issue is probably that the sunset is on the same day in the early morning hours. Because of this, there should be a yellow area at the center of the graph, but it's missing.

Data from SunCalc:
```
dawn: Invalid Date
dusk: Invalid Date
goldenHour: Date Tue Jun 21 2022 22:27:50 GMT+0000 (Greenwich Mean Time)
goldenHourEnd: Date Tue Jun 21 2022 04:41:21 GMT+0000 (Greenwich Mean Time)
nadir: Date Tue Jun 21 2022 01:34:36 GMT+0000 (Greenwich Mean Time)
nauticalDawn: Invalid Date
nauticalDusk: Invalid Date
night: Invalid Date
nightEnd: Invalid Date
solarNoon: Date Tue Jun 21 2022 13:34:36 GMT+0000 (Greenwich Mean Time)
sunrise: Date Tue Jun 21 2022 01:49:51 GMT+0000 (Greenwich Mean Time)
sunriseEnd: Date Tue Jun 21 2022 02:27:33 GMT+0000 (Greenwich Mean Time)
sunset: Date Wed Jun 22 2022 01:19:20 GMT+0000 (Greenwich Mean Time)
sunsetStart: Date Wed Jun 22 2022 00:41:39 GMT+0000 (Greenwich Mean Time)
```

Would be awesome to get this fixed so that I can create a correct graph for my home 👍

**Comment by leventerevesz** [comment]
Iceland causes quite a few complications 😅 

I need to add a new yellow and a new grey shape to the center to fix this. I'll see what I can do.

**Comment by leventerevesz** [comment]
There is a similar issue with sunrises before midnight, right?

**Comment by leobut** [comment]
I think generally speaking if `sunrise time` later than `sunset time` --> problem

I just played around with the time-zone field. Same issue there. If you take any location and move the timezone so far that e.g. noon matches midnight, half the day will be cut off because sunset will be before sunrise on the same day.

**Comment by leventerevesz** [comment]
I pushed an update  which adds the missing sunlight blob. It has some problems in more extreme scenarios but might be good enough for Iceland.

**Comment by leobut** [comment]
Thank you for this, this seems to work fine for my location 👍
